##
# Separate iOS and Android profiles to require platform specific page objects
##

android: PLATFORM=android -r features/support -r features/support/android -r features/step_definitions -e features/support/ios
ios: PLATFORM=ios APP_BUNDLE_PATH=build/example.app  -r features/support -r features/support/ios -r features/step_definitions -e features/support/android
